# Generated by Django 2.0.3 on 2018-05-22 13:36

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheetahNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview_image', models.FileField(upload_to='news/')),
                ('headlines', models.CharField(default='', max_length=50)),
                ('content', models.TextField(default='', max_length=50000)),
                ('pub_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            managers=[
                ('news', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='NewsPosters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('associate_images', models.FileField(upload_to='associate/')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('cheetah_news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.CheetahNew')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(default='', max_length=30)),
                ('players_image', models.FileField(upload_to='uploads/')),
                ('caption', models.TextField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            managers=[
                ('sliders', django.db.models.manager.Manager()),
            ],
        ),
        migrations.DeleteModel(
            name='PlayerSliders',
        ),
    ]
