# Generated by Django 2.0.3 on 2018-05-25 16:14

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20180522_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teams', models.CharField(default='', help_text='Team One VRS Team Two', max_length=300)),
                ('date', models.DateField(help_text='Date Of Match')),
                ('time', models.TimeField(help_text='Time Of Match')),
                ('venue', models.CharField(default='', help_text='Venue Of Match', max_length=150)),
                ('status', models.CharField(choices=[('Active', 'ACTIVE'), ('Inactive', 'INACTIVE')], default='Active', help_text='Show Or Hide Info Details', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            managers=[
                ('info_board', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PlayerOfWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, default='', max_length=30)),
                ('player_pic', models.FileField(upload_to='player_of_week/')),
                ('short_description', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
