# Generated by Django 2.0.3 on 2018-06-10 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_infoboard_playerofweek'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothLining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloth_name', models.CharField(blank=True, default='', help_text='Clothing Names (Optional)', max_length=30)),
                ('cloth_picture', models.FileField(upload_to='cloth_lining/')),
                ('pub_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StarReunion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(upload_to='reunion/')),
                ('caption', models.CharField(blank=True, default='', help_text='Star Reunion ..', max_length=120)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallpaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallpaper_image', models.FileField(upload_to='wallpapers/')),
                ('wallpaper_caption', models.CharField(blank=True, default='', help_text='Wallpapers Here', max_length=120)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
