# Generated by Django 2.0.3 on 2018-08-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_jerseyadvert_pictureofweek_sportsnew_talentbridgeadvert_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothlining',
            name='cloth_writeup',
            field=models.TextField(default=''),
        ),
    ]
