# Generated by Django 2.0.3 on 2018-08-13 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_clothlining_cloth_writeup'),
    ]

    operations = [
        migrations.CreateModel(
            name='CEOMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ceo_image', models.FileField(help_text="CEO's Message (Optional)", upload_to='ceo_pics/')),
                ('ceo_message', models.TextField(default='', max_length=65535)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
