# Generated by Django 2.0.3 on 2018-08-13 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_ceomessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceomessage',
            name='ceo_message_title',
            field=models.CharField(default='', help_text=' Enter Title Here', max_length=500),
        ),
    ]
