# Generated by Django 2.1 on 2018-08-16 04:09

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_ceomessage_ceo_message_title'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='ceomessage',
            managers=[
                ('messages', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='ceomessage',
            name='ceo_image',
            field=models.FileField(blank=True, help_text="CEO's Message (Optional)", upload_to='ceo_pics/'),
        ),
        migrations.AlterField(
            model_name='ceomessage',
            name='ceo_message_title',
            field=models.CharField(blank=True, default='', help_text=' Enter Title Here', max_length=500),
        ),
    ]
