# Generated by Django 2.1 on 2018-08-19 04:51

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20180816_0409'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(upload_to='first_team/%Y/%m/%d')),
                ('player_name', models.CharField(default='', help_text='Player Name Here ..', max_length=120)),
                ('profile', models.TextField(default='', help_text='Some small write up here ..', max_length=65535)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            managers=[
                ('first_team', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(upload_to='technical_team/%Y/%m/%d')),
                ('player_name', models.CharField(default='', help_text='Player Name Here ..', max_length=120)),
                ('profile', models.TextField(default='', help_text='Some small write up here ..', max_length=65535)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            managers=[
                ('technical_team', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='U13',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(upload_to='under13/%Y/%m/%d')),
                ('player_name', models.CharField(default='', help_text='Player Name Here ..', max_length=120)),
                ('profile', models.TextField(default='', help_text='Some small write up here ..', max_length=65535)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='U15',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(upload_to='under15/%Y/%m/%d')),
                ('player_name', models.CharField(default='', help_text='Player Name Here ..', max_length=120)),
                ('profile', models.TextField(default='', help_text='Some small write up here ..', max_length=65535)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='U17',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(upload_to='under17/%Y/%m/%d')),
                ('player_name', models.CharField(default='', help_text='Player Name Here ..', max_length=120)),
                ('profile', models.TextField(default='', help_text='Some small write up here ..', max_length=65535)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
