# Generated by Django 2.1 on 2018-08-19 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_firstteam_technicalteam_u13_u15_u17'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceomessage',
            name='ceo_message',
            field=models.TextField(blank=True, default='', max_length=65535),
        ),
        migrations.AlterField(
            model_name='firstteam',
            name='profile',
            field=models.TextField(blank=True, default='', help_text='Some small write up here ..', max_length=65535),
        ),
        migrations.AlterField(
            model_name='technicalteam',
            name='profile',
            field=models.TextField(blank=True, default='', help_text='Some small write up here ..', max_length=65535),
        ),
        migrations.AlterField(
            model_name='u13',
            name='profile',
            field=models.TextField(blank=True, default='', help_text='Some small write up here ..', max_length=65535),
        ),
        migrations.AlterField(
            model_name='u15',
            name='profile',
            field=models.TextField(blank=True, default='', help_text='Some small write up here ..', max_length=65535),
        ),
        migrations.AlterField(
            model_name='u17',
            name='profile',
            field=models.TextField(blank=True, default='', help_text='Some small write up here ..', max_length=65535),
        ),
    ]
