# Generated by Django 2.1 on 2018-08-19 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20180819_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoboard',
            name='score_board_team1',
            field=models.CharField(blank=True, default='', help_text=' Team One Results Here ..', max_length=2),
        ),
        migrations.AddField(
            model_name='infoboard',
            name='score_board_team2',
            field=models.CharField(blank=True, default='', help_text=' Team Two Results Here .. ', max_length=2),
        ),
    ]
