# Generated by Django 2.1 on 2018-08-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20180819_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheetahnew',
            name='published_by',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
