# Generated by Django 2.1 on 2018-08-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_cheetahnew_published_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PlayersAbroad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(upload_to='players_abroad/%Y/%m')),
                ('player_name', models.CharField(default='', help_text='Player Name Here ..', max_length=120)),
                ('profile', models.TextField(blank=True, default='', help_text='Some small write up here ..', max_length=65535)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
